import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import * as React from "react"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'AMRAP',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <ClerkProvider>    
      <html lang="en">
        <body className={inter.className} suppressHydrationWarning={true}>          
            {children}
        </body>
      </html>
    </ClerkProvider>
  )
}