import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuIndicator,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenuTrigger,
  NavigationMenuViewport,
} from "./(components)/ui/navigation-menu"
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'AMRAP',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
        <html lang="en">
          <body className={inter.className}>
          <div className="relative h-32 w-32 ...">
            <div className="absolute top-0 right-0 h-16 w-16 ...">
              <NavigationMenu>
                <NavigationMenuList>
                  <NavigationMenuItem>
                    <NavigationMenuTrigger>Sessions</NavigationMenuTrigger>
                    <NavigationMenuContent>
                      <NavigationMenuLink>
                        <Link href="/sessions"> My Sessions </Link>
                      </NavigationMenuLink>
                    </NavigationMenuContent>
                  </NavigationMenuItem>
                  <NavigationMenuItem>
                    <NavigationMenuTrigger>Profile</NavigationMenuTrigger>
                    <NavigationMenuContent>
                      <NavigationMenuLink>Link</NavigationMenuLink>
                    </NavigationMenuContent>
                  </NavigationMenuItem>
                  <NavigationMenuIndicator className="NavigationMenuIndicator" />
                </NavigationMenuList>
              </NavigationMenu>
              </div>
            </div>
            <main className="container mx-auto" >
              <div className="flex items-start justify-center min-h-screen">
                <div className="mt-20">
                  {children}
                </div>
              </div>
            </main>  
          </body>
        </html>
    </ClerkProvider>
  )
}

