import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'AMRAP',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
        <html lang="en">
          <body className={inter.className}>
            <main className="container mx-auto" >
              <div className="flex items-start justify-center min-h-screen mt-0">
                <div className="mt-0">
                  {children}
                </div>
              </div>
            </main>  
          </body>
        </html>
    </ClerkProvider>
  )
}

